### ISSUE TITLE
Child frame using tmux popup

### ISSUE THREAD

**Issue by dalgong** [gerd-moellmann/emacs-with-cl-packages#1]
Hi,
Regarding posframe support in terminal, I'm wondering if you have considered to use tmux popup feature ([a demo](https://www.reddit.com/r/tmux/comments/olgte7/floating_popups_in_tmux/)) in combination with `emacsclient -nw --eval ...` ?

Thanks,

**Comment by gerd-moellmann** [comment]
Jaeyoon Jeong ***@***.***> writes:

> Hi, Regarding posframe support in terminal, I'm wondering if you have
> considered to use tmux popup feature (a demo) in combination with
> emacsclient -nw --eval ... ?
>
> Thanks,

No, using that would be a different feature IMO and it would be
incompatible with the existing child frames on window systems. And i
twould be only for tmux, and so on.

(And what I have so far is working pretty well already, if I may say
that :-). As far as Posframe and Corfu go, which is what I'm mainly
interested in.)
